export default function CookiePolicyPage() {
  return (
    <div className="flex-1 bg-background pt-24 pb-32">
      <div className="container mx-auto px-6 max-w-4xl prose prose-lg prose-headings:font-heading prose-headings:font-bold prose-h2:text-2xl prose-h2:mt-12 prose-h2:mb-6 prose-p:text-foreground/80 prose-li:text-foreground/80">
        
        <h1 className="text-4xl md:text-5xl font-heading font-bold mb-4">Cookie Policy</h1>
        <p className="text-foreground/60 text-lg mb-12">No Books University | Last updated: {new Date().toLocaleDateString()}</p>

        <h2>What Are Cookies?</h2>
        <p>
          Cookies are small text files placed on your device when you visit a website. They help the website function, remember your preferences, and (for marketing cookies) measure how you interact with ads so we can improve them. This policy also covers similar technologies such as pixels and local storage, collectively referred to as "cookies" below.
        </p>

        <h2>Categories of Cookies We Use</h2>
        
        <h3>1. Strictly Necessary Cookies (Always On)</h3>
        <p>
          These are essential for the website to function. They enable core features like security, network management, and accessibility. You cannot switch these off in our systems. They do not store any personally identifiable information.
        </p>

        <h3>2. Analytics and Performance Cookies</h3>
        <p>
          These help us understand how visitors interact with our website by collecting and reporting information anonymously. They allow us to count visits, see which pages are popular, and understand where users might be running into errors. If you do not allow these, we will not know when you have visited our site and will not be able to monitor its performance.
        </p>

        <h3>3. Marketing and Tracking Cookies</h3>
        <p>
          We use performance marketing to acquire clients. To do this efficiently, we use third-party pixels (such as the Meta Pixel and Google tags) to track the actions you take on our site after viewing or clicking one of our ads. 
        </p>
        <p>
          This helps us:
        </p>
        <ul>
          <li>Measure the effectiveness of our advertising campaigns.</li>
          <li>Understand which ads lead to actual enquiries or sales.</li>
          <li>Show you relevant ads about our services on other platforms (retargeting).</li>
        </ul>
        <p>
          These cookies are set by our advertising partners. They do not store direct personal information (like your name or email) but they uniquely identify your browser and internet device. 
        </p>

        <h2>Third-Party Services</h2>
        <p>
          The analytics and marketing cookies described above are provided by third-party services. The information generated by these cookies about your use of our website will be transmitted to and stored by these providers in accordance with their own privacy policies. 
        </p>
        <p>Specifically, we use:</p>
        <ul>
          <li><strong>Google Analytics / Google Ads:</strong> To analyse traffic and measure ad conversions.</li>
          <li><strong>Meta (Facebook/Instagram) Pixel:</strong> To measure ad conversions and build retargeting audiences.</li>
        </ul>

        <h2>Managing Your Preferences</h2>
        <p>
          You have the right to choose whether or not to accept non-essential cookies.
        </p>
        <ul>
          <li><strong>Browser Settings:</strong> Most browsers allow you to view, manage, delete and block cookies for a website. Be aware that if you delete all cookies, any preferences you have set (including the preference not to be tracked) will be lost.</li>
          <li><strong>Opt-Out Links:</strong> You can opt out of personalised advertising from third-party networks through their respective platforms (e.g., Google Ad Settings, Meta Ad Preferences).</li>
        </ul>

        <h2>Contact Us</h2>
        <p>
          If you have any questions about our use of cookies, feel free to reach out to us at: join@nobooksuniversity.com
        </p>
        
        <div className="mt-12 p-6 bg-foreground/5 rounded-xl border border-foreground/10 text-center font-medium">
          By continuing to use our website, you acknowledge that you have read and understood this Cookie Policy.
        </div>
      </div>
    </div>
  )
}
